todo/config/routes.rb
Rails.application.routes.draw do
  resources :tasks

end

todo/app/models/task.rb
class Task < ActiveRecord::Base
end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'タスク登録完了しました' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'タスクの更新が完了しました' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content)
    end
end

todo/app/helpers/tasks_helper.rb
module TasksHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <!-- navigation bar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/tasks">RailsToDo</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/tasks">Home</a></li>
            <li><%= link_to "タスク登録", "/tasks/new"  %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    
    <div class="wrapper">
      <!-- ここからメインとなる部分の表示。2カラムのレイアウトにしてます -->
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span12">
            <div class="row-fluid">
              <div class="span2"></div>
              <div class="span10">
                <%= yield %>
              </div>            
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="push"></div>
    <!-- footer -->
    <div class="footer-wrapper">
      <div class="navbar navbar-fixed-bottom">
        <div class="container">
          <footer>
            <h3>about Me</h3>
            <div class="row-fluid">
              <div class="span2">
                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav">
                    <li><img src="<%= asset_path "facebook.png" %>" /></li>
                    <li><img src="<%= asset_path "twitter_bird.png" %>" /></li>

                  </ul>              
                </div>
              </div>
              <div class="span6"></div>
              <div class="span2"></div>
              <div class="span2"></div>
            </div>
            
          </footer>
        </div>
      </div>
		</div>
  </body>
</html>

todo/app/views/tasks/_form.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <div class="span6">
          <%= form_for(@task) do |f| %>
          <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
              <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <div class="field">

            <%= f.text_area :content , class: 'form-control', rows: '5' %>
          </div>
          <div class="actions">
            
            <% if request.path_info == "/tasks/new" then%>
              <%= f.submit "登録する" , class: 'btn  btn-primary' %>
              <%= link_to '<button type="button" class="btn btn-danger">中止する</button>'.html_safe, tasks_path %>

            <% else %>
              <%= link_to '<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-circle-arrow-left"></i>　一覧画面に戻る</button>'.html_safe, tasks_path %>
              <%= f.submit "更新する" , class: 'btn btn-danger' %>
            <% end %>
          </div>
          <% end %>

        </div>
      </div>
      
    </div>
  </div>
</div>

todo/app/views/tasks/edit.html.erb
<h1>タスクを編集する</h1>

<%= render 'form' %>

todo/app/views/tasks/index.html.erb
<h2>タスク一覧</h2>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span6">
            <table class="table table-striped">
              <tbody>
                <% @tasks.each do |task| %>
                <tr>
                  <td width="60%">
                    <%= task.content %>
                  </td>
                  <td>
                      <%= link_to '<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-info-sign"></i>　表示</button>'.html_safe, task %>
                    
                    <!-- <button type="button" class="btn btn-warning"> -->
                    <!--   <%= link_to 'Edit', edit_task_path(task) %> -->
                    <!-- </button> -->
                      <%= link_to '<button type="button" class="btn btn-danger"><i class="glyphicon glyphicon-remove-sign"></i>　削除</button>'.html_safe, task, method: :delete, data: { confirm: '本当に削除しますか?' } %>
                      <!-- <%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' } %> -->
                    </button>

                  </td>

                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

todo/app/views/tasks/new.html.erb
<h1>タスクを登録する</h1>

<%= render 'form' %>

todo/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div　class="container">
  <div class="row">
    <div class="col-sm-6 col-md-3">

      <article class="thumbnail">
        <img src="<%= asset_path "todo.jpg" %>" />
        <h3>タスク名： <%= @task.content %></h3>
        <p>
          <%= link_to '<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-edit"></i>　編集する</button>'.html_safe, edit_task_path(@task) %>

          <%= link_to '<button type="button" class="btn btn-danger">中止する</button>'.html_safe, tasks_path %>

        </p>

      </article>

    </div>
  </div>
</div>